Below is a database schema that includes the tables for Employee, Client, and Project with their respective columns. The schema also indicates primary keys (PK) and foreign keys (FK) where applicable, to maintain the relationships between the tables.

### Employee Table

- **Name** (PK): VARCHAR
- **Job Title**: VARCHAR
- **Department**: VARCHAR
- **SupervisorOrManager**: VARCHAR, FK (references Employee(Name))

### Client Table

- **Name** (PK): VARCHAR
- **Industry**: VARCHAR
- **Location**: VARCHAR

### Project Table

- **Name** (PK): VARCHAR
- **Location**: VARCHAR
- **StartDate**: DATE
- **EndDate**: DATE
- **Client**: VARCHAR, FK (references Client(Name))
- **ProjectDirector**: VARCHAR, FK (references Employee(Name))
- **ProjectManager**: VARCHAR, FK (references Employee(Name))

#### Notes:

- **Employee** table's `SupervisorOrManager` column is a self-referencing foreign key, implying that every employee's supervisor or manager is another employee within the same table. This setup supports a hierarchical structure within the company.
- **Client** table stores basic information about clients, including their industry and location.
- **Project** table links to both the **Employee** and **Client** tables. The `Client` column in the Project table is a foreign key referencing the Client table's primary key. Similarly, `ProjectDirector` and `ProjectManager` are foreign keys referencing the Employee table, indicating which employees are directing and managing the project, respectively.
- This schema assumes that project names, employee names, and client names are unique identifiers, serving as primary keys for their respective tables. In a real-world scenario, you might want to use numeric IDs as primary keys for scalability and privacy reasons and to handle duplicate names.

This schema forms the basis for a database that can track the relationships between employees, their roles in projects, and the clients those projects serve.

In [4]:

# Define your DDL statements
ddl_statements = """
CREATE TABLE Employee (
    Name VARCHAR(255) PRIMARY KEY,
    JobTitle VARCHAR(255) NOT NULL,
    Department VARCHAR(255) NOT NULL,
    SupervisorOrManager VARCHAR(255),
    FOREIGN KEY (SupervisorOrManager) REFERENCES Employee(Name)
);

CREATE TABLE Client (
    Name VARCHAR(255) PRIMARY KEY,
    Industry VARCHAR(255) NOT NULL,
    Location VARCHAR(255) NOT NULL
);

CREATE TABLE Project (
    Name VARCHAR(255) PRIMARY KEY,
    Location VARCHAR(255) NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE,
    Client VARCHAR(255) NOT NULL,
    ProjectDirector VARCHAR(255) NOT NULL,
    ProjectManager VARCHAR(255) NOT NULL,
    FOREIGN KEY (Client) REFERENCES Client(Name),
    FOREIGN KEY (ProjectDirector) REFERENCES Employee(Name),
    FOREIGN KEY (ProjectManager) REFERENCES Employee(Name)
);

ALTER TABLE Project
CHANGE COLUMN StartDate StartDate VARCHAR(255),
CHANGE COLUMN EndDate EndDate VARCHAR(255);
"""


# Execute the DDL
# with db_tool.engine.connect() as conn:
#     conn.execute(ddl_statements)

In [ ]:
# Employee Table
"""
INSERT INTO Employee (Name, JobTitle, Department, SupervisorOrManager) VALUES
('Dr. Helena Quantum', 'Chief Executive Officer (CEO)', 'Executive Management', NULL),
('Marcus Aurelius', 'Chief Operating Officer (COO)', 'Operations', 'Dr. Helena Quantum'),
('Nikola Tesla', 'Chief Technical Officer (CTO)', 'Technology and Innovation', 'Dr. Helena Quantum'),
('Ada Lovelace', 'Director of Engineering', 'Engineering', 'Nikola Tesla'),
('Rachel Carson', 'Director of Sustainability', 'Sustainability Initiatives', 'Marcus Aurelius'),
('Leonardo Da Vinci', 'Project Director', 'Special Projects', 'Ada Lovelace'),
('Marie Curie', 'Project Director', 'Research and Development Projects', 'Ada Lovelace'),
('Alan Turing', 'Project Manager', 'Technology Integration Projects', 'Leonardo Da Vinci'),
('Grace Hopper', 'Project Manager', 'Software Development for Engineering Tools', 'Leonardo Da Vinci'),
('Hedy Lamarr', 'Project Manager', 'Communication Systems Projects', 'Marie Curie'),
('George Washington Carver', 'Project Manager', 'Sustainable Materials Research', 'Marie Curie'),
('Isaac Newton', 'Assistant Project Manager', 'Physics Applications in Structural Design', 'Alan Turing'),
('Galileo Galilei', 'Assistant Project Manager', 'Observational Technologies for Construction', 'Grace Hopper'),
('Rosalind Franklin', 'Project Coordinator', 'Engineering Documentation and Compliance', 'Hedy Lamarr'),
('Mae Jemison', 'Project Coordinator', 'Space Utilization and Design', 'George Washington Carver'),
('Chien-Shiung Wu', 'Project Coordinator', 'Quantum Mechanics in Structural Engineering', 'Isaac Newton'),
('Gustave Eiffel', 'Lead Structural Engineer', 'Structural Engineering', 'Ada Lovelace'),
('Frank Lloyd Wright', 'Architectural Liaison Engineer', 'Architectural Integration', 'Ada Lovelace'),
('John Muir', 'Sustainability Consultant', 'Environmental Impact Analysis', 'Rachel Carson'),
('Greta Thunberg', 'Sustainability Consultant', 'Climate Change Adaptation Strategies', 'Rachel Carson'),
('Alexander Graham Bell', 'Structural Health Monitoring Engineer', 'Structural Integrity Assessment', 'Nikola Tesla'),
('Steve Jobs', 'Design Engineer', 'User Interface Design for Engineering Software', 'Nikola Tesla'),
('Leonardo Vinci', 'Design Engineer', 'Conceptual Design and Visualization', 'Nikola Tesla'),
('Henrietta Leavitt', 'BIM (Building Information Modeling) Manager', 'Digital Construction Management', 'Ada Lovelace'),
('Warren Buffett', 'Finance Manager', 'Finance', 'Marcus Aurelius'),
('Sheryl Sandberg', 'Human Resources Manager', 'Human Resources', 'Marcus Aurelius'),
('Don Draper', 'Marketing and Communications Manager', 'Marketing and Public Relations', 'Marcus Aurelius'),
('Linus Torvalds', 'IT Support Specialist', 'Information Technology', 'Nikola Tesla'),
('Ada Lovelace (IT)', 'IT Support Specialist', 'Information Technology', 'Nikola Tesla');
"""

# Client Table
"""INSERT INTO Client (Name, Industry, Location) VALUES ('Quantum Communications Corp', 'Technology and Communications Infrastructure', 'Silicon Valley, USA');
INSERT INTO Client (Name, Industry, Location) VALUES ('Skyline Developers', 'Real Estate', 'Dubai, UAE');
INSERT INTO Client (Name, Industry, Location) VALUES ('Blue Horizon Hotels', 'Hospitality', 'Maldives');
INSERT INTO Client (Name, Industry, Location) VALUES ('Greenworld Resorts', 'Hospitality', 'Costa Rica');
INSERT INTO Client (Name, Industry, Location) VALUES ('Pinnacle Health Group', 'Healthcare and Hospital', 'London, UK');
INSERT INTO Client (Name, Industry, Location) VALUES ('Future Tech Innovations', 'Technology and Communications Infrastructure', 'Tokyo, Japan');
INSERT INTO Client (Name, Industry, Location) VALUES ('Urban Oasis Developments', 'Real Estate', 'New York City, USA');
INSERT INTO Client (Name, Industry, Location) VALUES ('Serene Stays Hospitality', 'Hospitality', 'Paris, France');
INSERT INTO Client (Name, Industry, Location) VALUES ('Vista Healthcare Solutions', 'Healthcare and Hospital', 'Mumbai, India');
INSERT INTO Client (Name, Industry, Location) VALUES ('EcoSpace Real Estate', 'Real Estate', 'Sydney, Australia');
"""

"""
INSERT INTO Project (Name, Location, StartDate, EndDate, Client, ProjectDirector, ProjectManager) VALUES
('Quantum Data Center Expansion', 'Palo Alto, USA', '2023-01-15', '2024-06-30', 'Quantum Communications Corp', 'Leonardo Da Vinci', 'Alan Turing'),
('Dubai Skyline Tower', 'Dubai, UAE', '2022-09-01', '2025-12-31', 'Skyline Developers', 'Marie Curie', 'Grace Hopper'),
('Blue Lagoon Luxury Resort', 'Baa Atoll, Maldives', '2023-04-01', '2025-05-20', 'Blue Horizon Hotels', 'Leonardo Da Vinci', 'Hedy Lamarr'),
('Eco Retreat Development', 'Guanacaste, Costa Rica', '2022-11-15', '2024-08-30', 'Greenworld Resorts', 'Marie Curie', 'George Washington Carver'),
('Central City Medical Hub', 'London, UK', '2021-07-01', '2023-09-30', 'Pinnacle Health Group', 'Leonardo Da Vinci', 'Alan Turing'),
('Innovative Tech Park', 'Shibuya, Tokyo, Japan', '2023-02-01', '2025-03-15', 'Future Tech Innovations', 'Marie Curie', 'Grace Hopper'),
('Metropolitan Luxury Apartments', 'Manhattan, New York City, USA', '2022-05-01', '2024-12-31', 'Urban Oasis Developments', 'Leonardo Da Vinci', 'Hedy Lamarr'),
('Champs-Élysées Boutique Hotel', 'Paris, France', '2023-03-01', '2024-10-30', 'Serene Stays Hospitality', 'Marie Curie', 'George Washington Carver'),
('Advanced Health Research Facility', 'Mumbai, India', '2023-01-10', '2024-07-25', 'Vista Healthcare Solutions', 'Leonardo Da Vinci', 'Alan Turing'),
('Harbour View Green Spaces', 'Sydney, Australia', '2022-08-01', '2025-02-20', 'EcoSpace Real Estate', 'Marie Curie', 'Grace Hopper');
"""